### ISSUE TITLE
xiaofang hack have only sound  but not display image when i run via vlc,...

### ISSUE THREAD

**Issue by baoson202** [samtap/fang-hacks#220] opened 2017-09-03 09:32 UTC
xiaofang hack have only sound  but not display image when i run via vlc,...
Please help me !

**Comment by Chrischi-** [comment] 2017-09-03 09:47
I think this is no "code" related issue. Try changing the resolution and or the bitrate.

For questions, suggestions or just general discussion, please join #fanghacks on irc.freenode.net There's also a discord channel: https://discord.gg/xhRzpPn

**Comment by samtap** [comment] 2017-09-06 13:22
@baoson202 Chrischi is correct, it's working for many others so likely a local problem and not a bug, which is why I'm closing it.

If you still need help you should run vlc with increased debug logging, which usually provides some hints. Post the logs somewhere (pastebin) and link to it on discord and you may find someone there who's seen it before and is able to help you.

**Closed by samtap** 2017-09-06 13:22 UTC
